import { cssr } from 'dsh-tauri-ui/client'

const { c, bem: { b, e, m } } = cssr

/** 侧栏整槽克隆（sidebar root）：logo 行 + 面板区 + 官方子槽透传。 */
export default b('panel', {
  '--dshp-padding': '12px',
  'height': '100%',
  'padding': '6px var(--dshp-padding)',
  'boxSizing': 'border-box',
  'background': 'var(--dsw-specific-sidebar-fill)',
  'color': 'var(--dsw-alias-label-primary)',
  '--dsh-scrollbar-thumb': 'var(--dsw-alias-scrollbar-bg-l2)',
  '--dsh-scrollbar-thumb-hover': 'var(--dsw-alias-scrollbar-hover-l2)',
  'flexDirection': 'column',
  'fontSize': '14px',
  'display': 'flex',
  '--dsh-sidebar-inline-padding': 'var(--dshp-padding)',
}, [
  e('section-header', {
    boxSizing: 'border-box',
    height: '36px',
    color: 'var(--dsw-alias-label-tertiary)',
    borderRadius: '12px',
    flex: 'none',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '4px',
    paddingLeft: '8px',
    display: 'flex',
    overflow: 'hidden',
  }),
  e('section-header-title', {
    whiteSpace: 'nowrap',
    opacity: 1,
    visibility: 'visible',
    minWidth: 0,
    maxWidth: '45%',
    transition: 'max-width .18s var(--ds-ease-in-out), margin-right .18s var(--ds-ease-in-out), opacity .12s var(--ds-ease-in-out), transform .18s var(--ds-ease-in-out), visibility 0s linear',
    flex: 'none',
    lineHeight: '20px',
    overflow: 'hidden',
  }),
  e('logo-row', {
    boxSizing: 'border-box',
    flex: 'none',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '8px',
    height: '60px',
    marginBottom: '4px',
    padding: '4px 0 4px 4px',
    display: 'flex',
    overflow: 'hidden',
  }),
  e('brand', {
    minWidth: 0,
    color: 'inherit',
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    flex: 1,
    alignItems: 'center',
    padding: 0,
    display: 'inline-flex',
    overflow: 'hidden',
  }),
  e('brand-identity', {
    alignItems: 'center',
    gap: '8px',
    minWidth: 0,
    height: '24px',
    display: 'inline-flex',
  }),
  e('brand-mark', {
    flex: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
  }),
  e('brand-name', {
    letterSpacing: '.04em',
    alignItems: 'center',
    gap: '6px',
    minWidth: 0,
    height: '24px',
    fontSize: '18px',
    fontWeight: 600,
    lineHeight: '24px',
    display: 'inline-flex',
  }),
  e('fallback-brand-name', {
    letterSpacing: 0,
    whiteSpace: 'nowrap',
    fontSize: '17px',
  }),
  e('icon-button', {
    cursor: 'pointer',
    width: '28px',
    height: '28px',
    color: 'var(--dsw-alias-label-secondary)',
    background: 'transparent',
    border: 'none',
    borderRadius: '50%',
    flex: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    display: 'inline-flex',
  }, [
    c('&:hover', { background: 'var(--dsw-alias-interactive-bg-hover)' }),
  ]),
  e('rail-mark', {
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
  }),
  e('panel-area', {
    flex: 'none',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '2px',
    margin: 0,
    display: 'flex',
    marginRight: 'var(--dsh-session-list-scrollbar-offset)',
    paddingLeft: '4px',
    paddingRight: 'calc(var(--dsh-session-list-edge-inset) - var(--dsh-session-list-scrollbar-width) - var(--dsh-session-list-scrollbar-offset))',
  }),
  e('menu-item', {
    boxSizing: 'border-box',
    appearance: 'none',
    cursor: 'pointer',
    userSelect: 'none',
    width: '100%',
    minWidth: 0,
    height: '34px',
    flex: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '0 8px',
    border: 0,
    borderRadius: '8px',
    overflow: 'hidden',
    background: 'transparent',
    color: 'var(--dsw-alias-label-primary)',
    fontFamily: 'inherit',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '22px',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    transition: 'background-color .12s var(--ds-ease-in-out), color .12s var(--ds-ease-in-out)',
  }, [
    c('&:hover', { background: 'var(--dsw-alias-interactive-bg-hover)' }),
    c('&:focus-visible', { outline: '2px solid var(--dsw-alias-border-focus)', outlineOffset: '-2px' }),
    m('selected', { background: 'var(--dsw-alias-interactive-bg-hover)' }),
  ]),
  e('new-session', {
    width: '100%',
    height: '38px',
    margin: '0 0 4px',
    padding: '8px 16px',
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: '12px',
    background: 'var(--dsw-alias-button-elevated-fill)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 500,
  }, [
    c('&:hover', { background: 'var(--dsw-alias-button-floating-hover)' }),
  ]),
  e('menu-item-icon', {
    boxSizing: 'border-box',
    flex: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'inline-flex',
    fontSize: '16px',
  }),
  e('menu-item-label', {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    margin: '0 6px 0 0',
  }),
  e('region-area', {
    minHeight: 0,
    marginRight: 'calc(-1 * var(--dshp-padding))',
    flexDirection: 'column',
    flex: 1,
    padding: '0 4px',
    display: 'flex',
    overflow: 'hidden',
  }),
  e('foot-area', {
    flexDirection: 'column',
    flex: 'none',
    display: 'flex',
  }),
  e('footer-actions', {
    flex: 'none',
    width: '100%',
    minWidth: 0,
    display: 'flex',
  }),
  e('settings-area', {
    flex: 'none',
    width: '100%',
    minWidth: 0,
  }),
  e('panel-view', {
    'height': '100%',
    'boxSizing': 'border-box',
    'minWidth': 0,
    'overflowY': 'auto',
    'scrollbarGutter': 'stable',
    'position': 'relative',
    // 内容宽度派生（自给自足镜像 alpha）：有拖拽偏好用偏好，否则自适应
    // clamp(680px, col*0.64, 920px)；列宽与偏好由 width 控制器发布。
    '--dsh-chat-content-width': 'var(--dsh-chat-user-width, clamp(680px, calc(var(--dsh-conversation-column-width, 0px) * .64), 920px))',
  }),
  e('panel-view-column', {
    maxWidth: 'var(--dsh-chat-content-width,780px)',
    minHeight: '100%',
    width: '100%',
    margin: '0 auto',
    flexDirection: 'column',
    gap: '16px',
    display: 'flex',
  }),
  // 内容宽度拖拽手柄（镜像 alpha WidthHandle）：绝对定位在内容列两侧 24px 外，
  // 宽度自适应（列宽 − 内容宽的一半再减两个 24px inset，最多 40px）；
  // hover/拖动时发光条跟随指针 Y（--dsh-width-handle-pointer-y）。
  e('width-handle', {
    zIndex: 8,
    width: 'min(40px, calc((100% - var(--dsh-chat-content-width)) / 2 - 24px - 24px))',
    cursor: 'col-resize',
    position: 'absolute',
    top: 0,
    bottom: 0,
  }, [
    c('&[data-side="left"]', { right: 'calc(50% + var(--dsh-chat-content-width) / 2 + 24px)' }),
    c('&[data-side="right"]', { left: 'calc(50% + var(--dsh-chat-content-width) / 2 + 24px)' }),
    c('&:after', {
      content: '""',
      background: 'linear-gradient(to bottom, transparent calc(var(--dsh-width-handle-pointer-y, 50%) - 52px), var(--dsw-alias-scrollbar-hover-l1) calc(var(--dsh-width-handle-pointer-y, 50%) - 12px), var(--dsw-alias-scrollbar-hover-l1) calc(var(--dsh-width-handle-pointer-y, 50%) + 12px), transparent calc(var(--dsh-width-handle-pointer-y, 50%) + 52px))',
      opacity: 0,
      pointerEvents: 'none',
      borderRadius: '3px',
      width: '3px',
      position: 'absolute',
      top: 0,
      bottom: 0,
    }),
    c('&[data-side="left"]:after', { right: '16px' }),
    c('&[data-side="right"]:after', { left: '16px' }),
    c('&:hover:after, &[data-dragging]:after', { opacity: 1 }),
  ]),
  m('collapsed', [
    c('&', { padding: '18px 10px 6px' }),
    c('& .dshp-panel__section-header-title', { opacity: 0, visibility: 'hidden', maxWidth: 0 }),
    c('& .dshp-panel__logo-row', { justifyContent: 'flex-start', height: '40px', marginBottom: '4px', padding: 0 }),
    c('& .dshp-panel__icon-button', { width: '36px', height: '36px', color: 'var(--dsw-alias-label-primary)' }),
    c('& .dshp-panel__panel-area', { alignItems: 'center', gap: '4px', marginBottom: '12px', paddingLeft: 0 }),
    c('& .dshp-panel__menu-item', {
      justifyContent: 'center',
      alignSelf: 'flex-start',
      width: '36px',
      minWidth: '36px',
      height: '36px',
      padding: 0,
      gap: 0,
      borderRadius: '12px',
    }),
    c('& .dshp-panel__menu-item-label', { display: 'none' }),
    c('& .dshp-panel__menu-item-icon', {
      fontSize: '18px',
      color: 'var(--dsw-alias-label-primary)',
    }),
    c('& .dshp-panel__new-session', {
      borderColor: 'transparent',
      justifyContent: 'center',
      width: '36px',
      height: '36px',
      margin: 0,
      padding: 0,
      gap: 0,
    }),
    c('& .dshp-panel__region-area', { marginLeft: 0, marginRight: 0, padding: 0 }),
    c('& .dshp-panel__foot-area', { alignItems: 'center' }),
    c('& .dshp-panel__settings-area, & .dshp-panel__footer-actions', { justifyContent: 'center', width: 'auto', display: 'flex' }),
  ]),
  m('wide', [
    c('&', { width: 'var(--dshp-width)' }),
  ]),
  m('quiet-bars', [
    c('&', { '--dsh-scrollbar-thumb': 'transparent', '--dsh-scrollbar-thumb-hover': 'transparent' }),
  ]),
  m('fading', [
    c('& > *', { opacity: 0, transition: 'opacity .15s var(--ds-ease-in-out)' }),
  ]),
  c('@keyframes dshp-rail-in', [c('from', { opacity: 0, transform: 'translate(49px)' })]),
  c('@keyframes dshp-rail-fade-in', [c('from', { opacity: 0 })]),
  c('@media (prefers-reduced-motion: reduce)', [
    c('.dshp-panel--fading > *', { transition: 'none' }),
    c('.dshp-panel--rail-in .dshp-panel__icon-button, .dshp-panel--rail-in .dshp-panel__menu-item, .dshp-panel--rail-in .dshp-panel__foot-area, .dshp-panel--rail-in .dshp-panel__region-area', { animation: 'none' }),
  ]),
])
