import { cssr, styles as sharedStyles } from 'dsh-tauri-ui/client'

const { c, bem: { b, e, m } } = cssr
const {
  primary,
  secondary,
  tertiary,
  borderL2: border,
  business,
  layer1,
  layer3,
  hover,
} = sharedStyles

/** 扩展面板：Tabs 布局 + 技能/MCP 卡片 + 编辑器/导入弹窗内容。 */
export default b('extension', [
  e('section', {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
    maxWidth: '760px',
    color: primary,
  }),
  e('tabs', {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '22px',
    borderBottom: `1px solid ${border}`,
    marginTop: '2px',
  }),
  e('tab', {
    position: 'relative',
    border: '0',
    padding: '7px 1px 9px',
    background: 'transparent',
    color: tertiary,
    font: 'inherit',
    fontSize: '13px',
    lineHeight: '20px',
    cursor: 'pointer',
  }, [
    c('&:hover, &[data-active="true"]', { color: primary }),
    c('&[data-active="true"]::after, &:focus-visible::after', {
      position: 'absolute',
      right: '0',
      bottom: '-1px',
      left: '0',
      height: '2px',
      borderRadius: '2px 2px 0 0',
      background: primary,
      content: '""',
    }),
    c('&:focus-visible', {
      outline: `2px solid ${business}`,
      outlineOffset: '2px',
      borderRadius: '2px',
      color: primary,
    }),
  ]),
  e('tab-panel', { minWidth: '0', paddingTop: '2px' }),
  e('head', {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  }, [
    c('& h3', { margin: '0', fontSize: '13px', lineHeight: '20px', fontWeight: '600' }),
    c('& > svg', { flex: 'none', color: tertiary }),
  ]),
  e('list-head', {
    display: 'flex',
    alignItems: 'baseline',
    gap: '7px',
    padding: '0 2px',
    marginTop: '2px',
  }, [
    c('& h3', { margin: '0', fontSize: '13px', lineHeight: '20px', fontWeight: '600' }),
  ]),
  e('intro', {
    margin: '0',
    fontSize: '13px',
    lineHeight: '20px',
    color: tertiary,
  }),
  e('empty', {
    margin: '0',
    fontSize: '13px',
    lineHeight: '20px',
    color: tertiary,
  }),
  e('count', {
    fontSize: '12px',
    lineHeight: '18px',
    color: tertiary,
    fontVariantNumeric: 'tabular-nums',
  }),
  e('spacer', { flex: '1' }),
  e('refresh', {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    border: '0',
    borderRadius: '6px',
    background: 'transparent',
    color: tertiary,
    cursor: 'pointer',
    textDecoration: 'none',
  }, [
    c('&:hover', { background: hover, color: primary }),
    c('&:focus-visible', { outline: `2px solid ${business}`, outlineOffset: '-2px' }),
  ]),
  e('icon-link', {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    border: '0',
    borderRadius: '6px',
    background: 'transparent',
    color: tertiary,
    cursor: 'pointer',
    textDecoration: 'none',
  }, [
    c('&:hover', { background: hover, color: primary }),
    c('&:focus-visible', { outline: `2px solid ${business}`, outlineOffset: '-2px' }),
  ]),
  e('cards', {
    display: 'grid',
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    alignItems: 'stretch',
    gap: '10px',
    margin: '0',
    padding: '0',
    listStyle: 'none',
  }, [
    m('single', { gridTemplateColumns: 'minmax(0,1fr)' }),
  ]),
  e('card', {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '0',
    border: `1px solid ${border}`,
    borderRadius: '10px',
    background: layer3,
    padding: '12px 14px',
  }, [
    c('&:hover', { background: hover }),
    m('muted', { opacity: '.55' }),
  ]),
  e('card-top', {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  }),
  e('card-row', {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  }),
  e('card-title', {
    flex: '1',
    minWidth: '0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '14px',
    lineHeight: '20px',
    fontWeight: '600',
    fontFamily: 'var(--ds-font-family-code)',
  }),
  e('card-desc', {
    margin: '0',
    fontSize: '12px',
    lineHeight: '18px',
    color: secondary,
    display: '-webkit-box',
    WebkitLineClamp: '2',
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  }),
  e('tag', {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '20px',
    borderRadius: '5px',
    padding: '1px 6px',
    background: layer1,
    color: secondary,
    fontSize: '11px',
    lineHeight: '16px',
    whiteSpace: 'nowrap',
  }, [
    c('&[data-kind="source"]', {
      background: `color-mix(in srgb,${business} 10%,transparent)`,
      color: business,
    }),
    c('&[data-kind="off"]', {
      background: 'color-mix(in srgb,var(--dsw-alias-state-warning-primary,var(--dsw-alias-label-tertiary)) 12%,transparent)',
      color: secondary,
    }),
  ]),
  e('banner', {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '10px 12px',
    background: layer3,
    fontSize: '13px',
    lineHeight: '20px',
  }, [
    c('&[data-kind="ok"]', {
      borderColor: 'color-mix(in srgb,var(--dsw-alias-state-success-primary) 35%,transparent)',
      background: 'color-mix(in srgb,var(--dsw-alias-state-success-primary) 8%,transparent)',
    }),
    c('&[data-kind="error"]', {
      borderColor: 'color-mix(in srgb,var(--dsw-alias-state-error-primary) 35%,transparent)',
      background: 'color-mix(in srgb,var(--dsw-alias-state-error-primary) 8%,transparent)',
    }),
    c('&[data-kind="info"]', {
      borderColor: `color-mix(in srgb,${business} 35%,transparent)`,
      background: `color-mix(in srgb,${business} 8%,transparent)`,
    }),
  ]),
  e('banner-body', {
    flex: '1',
    minWidth: '0',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  }),
  e('banner-hint', {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    color: secondary,
    fontSize: '12px',
    lineHeight: '18px',
  }),
  e('form', { display: 'flex', flexDirection: 'column', gap: '10px' }),
  e('editor-tabs', {
    display: 'flex',
    gap: '4px',
    borderBottom: `1px solid ${border}`,
  }),
  e('editor-tab', {
    position: 'relative',
    border: '0',
    padding: '7px 10px 9px',
    background: 'transparent',
    color: tertiary,
    font: 'inherit',
    fontSize: '13px',
    lineHeight: '20px',
    cursor: 'pointer',
  }, [
    c('&:hover, &[data-active="true"]', { color: primary }),
    c('&[data-active="true"]::after', {
      position: 'absolute',
      right: '8px',
      bottom: '-1px',
      left: '8px',
      height: '2px',
      borderRadius: '2px 2px 0 0',
      background: primary,
      content: '""',
    }),
    c('&:focus-visible', {
      outline: `2px solid ${business}`,
      outlineOffset: '-2px',
      borderRadius: '4px',
      color: primary,
    }),
  ]),
  e('label', {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    fontSize: '12px',
    lineHeight: '18px',
    color: secondary,
  }, [
    c('& > span:first-child', { color: tertiary }),
  ]),
  e('input', {
    width: '100%',
    boxSizing: 'border-box',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '7px 10px',
    outline: 'none',
    background: layer1,
    color: primary,
    font: 'inherit',
    fontSize: '13px',
  }, [
    c('&:focus-visible', {
      borderColor: business,
      boxShadow: `0 0 0 2px color-mix(in srgb,${business} 18%,transparent)`,
    }),
  ]),
  e('textarea', {
    width: '100%',
    boxSizing: 'border-box',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '7px 10px',
    outline: 'none',
    background: layer1,
    color: primary,
    font: 'inherit',
    fontSize: '13px',
    minHeight: '320px',
    resize: 'vertical',
    fontFamily: 'var(--ds-font-family-code)',
    lineHeight: '1.5',
  }, [
    c('&[data-short="true"]', { minHeight: '96px' }),
    c('&:focus-visible', {
      borderColor: business,
      boxShadow: `0 0 0 2px color-mix(in srgb,${business} 18%,transparent)`,
    }),
  ]),
  e('select', {
    width: '100%',
    boxSizing: 'border-box',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '7px 10px',
    outline: 'none',
    background: layer1,
    color: primary,
    font: 'inherit',
    fontSize: '13px',
  }, [
    c('&:focus-visible', {
      borderColor: business,
      boxShadow: `0 0 0 2px color-mix(in srgb,${business} 18%,transparent)`,
    }),
  ]),
  e('search', {
    width: '200px',
    boxSizing: 'border-box',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '4px 10px',
    outline: 'none',
    background: layer1,
    color: primary,
    font: 'inherit',
    fontSize: '12px',
    lineHeight: '18px',
  }, [
    c('&:focus-visible', {
      borderColor: business,
      boxShadow: `0 0 0 2px color-mix(in srgb,${business} 18%,transparent)`,
    }),
  ]),
  e('json-editor', { minHeight: '260px' }),
  e('checks', {
    display: 'flex',
    gap: '16px',
    fontSize: '13px',
    lineHeight: '20px',
  }, [
    c('& label', {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '8px',
      cursor: 'pointer',
      minWidth: '0',
    }),
  ]),
  e('import-choice', {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    minWidth: '0',
  }, [
    m('disabled', { cursor: 'default' }),
  ]),
  e('form-error', {
    margin: '0',
    color: 'var(--dsw-alias-state-error-primary)',
    fontSize: '12px',
    lineHeight: '18px',
  }),
  // Modal className 需高于官方 Modal 内部宽度的特异性，保持双重类。
  c('.dshp-extension__modal-wide.dshp-extension__modal-wide', { width: 'min(680px,100%)' }),
  c('.dshp-extension__modal-form.dshp-extension__modal-form', { width: 'min(760px,100%)' }),
  c('.dshp-extension__modal-scroll.dshp-extension__modal-scroll', { maxHeight: 'calc(100vh - 160px)', overflowY: 'auto' }),
  e('md-preview', {
    minHeight: '320px',
    maxHeight: '60vh',
    overflowY: 'auto',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '8px 12px',
    background: layer1,
    fontSize: '13px',
  }),
  e('md-body', [
    c('& h1, & h2, & h3, & h4', { margin: '14px 0 6px', color: primary, lineHeight: '1.4' }),
    c('& h1', { fontSize: '18px' }),
    c('& h2', { fontSize: '16px' }),
    c('& h3', { fontSize: '14px' }),
    c('& h4', { fontSize: '13px' }),
    c('& p', { margin: '6px 0', lineHeight: '20px' }),
    c('& ul, & ol', { margin: '6px 0', paddingLeft: '20px' }),
    c('& code', {
      fontFamily: 'var(--ds-font-family-code)',
      fontSize: '12px',
      background: layer3,
      borderRadius: '4px',
      padding: '1px 5px',
    }),
    c('& pre', {
      margin: '8px 0',
      padding: '10px 12px',
      overflowX: 'auto',
      border: `1px solid ${border}`,
      borderRadius: '8px',
      background: layer3,
    }),
    c('& a', { color: business }),
  ]),
  e('code', {
    fontFamily: 'var(--ds-font-family-code)',
    fontSize: '11px',
    lineHeight: '17px',
    whiteSpace: 'pre',
    margin: '8px 0',
    padding: '10px 12px',
    overflowX: 'auto',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    background: layer3,
  }),
  e('import-scroll', {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    maxHeight: 'min(400px,52vh)',
    overflowY: 'auto',
    padding: '2px 4px 2px 2px',
  }),
  e('import-group', { display: 'flex', flexDirection: 'column', gap: '8px' }),
  e('import-head', { display: 'flex', alignItems: 'center', gap: '8px', padding: '0 2px' }),
  e('import-count', { fontSize: '12px', lineHeight: '18px', color: tertiary }),
  e('import-all', {
    marginLeft: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: secondary,
    cursor: 'pointer',
  }),
  e('chips', {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  }),
  e('chip', {
    border: `1px solid ${border}`,
    borderRadius: '999px',
    padding: '2px 10px',
    background: 'transparent',
    color: secondary,
    font: 'inherit',
    fontSize: '12px',
    cursor: 'pointer',
  }, [
    c('&:hover, &[data-active="true"]', { color: business, background: hover }),
  ]),
  e('switch', {
    position: 'relative',
    flex: 'none',
    width: '30px',
    height: '18px',
    border: '0',
    borderRadius: '999px',
    background: layer1,
    boxShadow: `inset 0 0 0 1px ${border}`,
    cursor: 'pointer',
  }, [
    c('&[aria-checked="true"]', {
      background: `color-mix(in srgb,${business} 55%,transparent)`,
      boxShadow: 'none',
    }),
    c('&[aria-checked="true"] .dshp-extension__switch-knob', { left: '14px', background: '#fff' }),
  ]),
  e('switch-knob', {
    position: 'absolute',
    top: '2px',
    left: '2px',
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    background: primary,
    transition: 'left .15s',
  }),
  e('link', {
    border: '0',
    padding: '0',
    background: 'transparent',
    font: 'inherit',
    fontSize: '12px',
    lineHeight: '18px',
    cursor: 'pointer',
    textDecoration: 'none',
    color: business,
  }, [
    c('&:hover', { textDecoration: 'underline' }),
  ]),
  e('segments', {
    display: 'inline-flex',
    gap: '4px',
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '3px',
    background: layer1,
  }),
  e('segment', {
    border: '0',
    borderRadius: '6px',
    padding: '4px 14px',
    background: 'transparent',
    color: secondary,
    font: 'inherit',
    fontSize: '12px',
    cursor: 'pointer',
  }, [
    c('&[data-active="true"]', { background: hover, color: primary, fontWeight: '600' }),
  ]),
  e('format', {
    border: `1px solid ${border}`,
    borderRadius: '8px',
    padding: '8px 12px',
    background: layer1,
  }, [
    c('& summary', { fontSize: '12px', color: secondary, cursor: 'pointer' }),
  ]),
  e('format-hint', { margin: '2px 0 0', fontSize: '12px', color: tertiary }),
  c('@media (max-width: 680px)', [
    c('.dshp-extension__cards', { gridTemplateColumns: 'minmax(0,1fr)' }),
    c('.dshp-extension__search', { width: '140px' }),
  ]),
])
