import { cssr } from 'dsh-tauri-ui/client'

const { bem: { b, e, m } } = cssr

/** 工作树状态条（surface）与检出/放弃弹窗（dialog）样式。 */
export default b('worktree', [
  e('surface', {
    boxSizing: 'border-box',
    width: 'calc(100% - 2 * var(--dsh-composer-side-clearance) - 4 * var(--dsh-composer-dock-inset))',
    maxWidth: 'calc(var(--dsh-composer-card-max-width) - 4 * var(--dsh-composer-dock-inset))',
    margin: '0 auto',
    alignSelf: 'center',
  }),
  e('surface-bar', {
    boxSizing: 'border-box',
    width: '100%',
    position: 'relative',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '4px 5px 4px 12px',
    margin: '0 auto',
    border: '1px solid var(--dsw-alias-border-l1)',
    borderRadius: '12px',
    background: 'var(--dsw-specific-tip)',
    color: 'var(--dsw-alias-label-primary)',
    pointerEvents: 'auto',
  }),
  e('surface-content', { display: 'flex', alignItems: 'center', gap: '5px' }),
  e('surface-label', { fontSize: '13px', lineHeight: '20px', fontWeight: 500 }),
  e('action', {
    height: '26px',
    padding: '0 10px',
    border: 'none',
    borderRadius: '7px',
    fontFamily: 'inherit',
    fontSize: '12px',
    cursor: 'pointer',
    color: 'var(--dsw-alias-label-primary)',
    background: 'var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,0.08))',
    whiteSpace: 'nowrap',
  }, [
    m('log', { padding: 0, fontSize: '13px', background: 'transparent', textDecoration: 'underline' }),
    m('danger', { color: 'var(--dsw-alias-danger-foreground, #c0392b)', background: 'transparent' }),
  ]),
  e('spacer', { flex: 1 }),
  e('logs', {
    display: 'grid',
    gridTemplateRows: '0fr',
    opacity: 0,
    transition: 'grid-template-rows 180ms cubic-bezier(.16, 1, .3, 1), opacity 140ms ease',
  }, [
    m('open', { gridTemplateRows: '1fr', opacity: 1 }),
  ]),
  e('logs-inner', { minHeight: 0, overflow: 'hidden' }),
  e('logs-panel', {
    maxHeight: '180px',
    overflowY: 'auto',
    padding: '10px',
    borderRadius: '10px',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-base)',
    zIndex: 30,
  }),
  e('log-line', { fontSize: '12px', fontFamily: 'cursive', lineHeight: '16px' }),
  e('modal', {
    position: 'absolute',
    inset: 0,
    zIndex: 1000,
    display: 'grid',
    placeItems: 'center',
    background: 'rgba(0,0,0,0.4)',
  }),
  e('dialog-card', {
    boxSizing: 'border-box',
    width: 'min(460px, calc(100vw - 48px))',
    padding: '20px 22px',
    borderRadius: '16px',
    background: 'var(--dsw-alias-bg-base)',
    color: 'var(--dsw-alias-label-primary)',
    boxShadow: '0 24px 64px rgba(0,0,0,0.28)',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  }),
  e('dialog-title', { fontSize: '16px', fontWeight: 600, lineHeight: '24px', margin: 0 }),
  e('dialog-body', { fontSize: '13px', lineHeight: '20px', color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))', margin: 0 }),
  e('dialog-field', { display: 'flex', flexDirection: 'column', gap: '6px' }),
  e('dialog-field-label', { fontSize: '12px', lineHeight: '18px', color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))' }),
  e('dialog-input-wrap', {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    border: '1px solid var(--dsw-alias-border-weak, rgba(127,127,127,0.25))',
    borderRadius: '10px',
    overflow: 'hidden',
    background: 'var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,0.06))',
  }),
  e('dialog-input', {
    flex: 1,
    minWidth: 0,
    height: '36px',
    padding: '0 10px',
    border: 'none',
    background: 'none',
    color: 'var(--dsw-alias-label-primary)',
    fontFamily: 'inherit',
    fontSize: '13px',
    outline: 'none',
  }),
  e('dialog-path-row', { display: 'flex', justifyContent: 'space-between', gap: '12px', fontSize: '12px', lineHeight: '18px' }),
  e('dialog-path-key', { flex: 'none', color: 'var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary))' }),
  e('dialog-path-value', { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontFamily: 'monospace' }),
  e('dialog-error', { fontSize: '12px', lineHeight: '18px', color: '#c0392b' }),
  e('dialog-footer', { display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '4px' }),
  e('dialog-button', {
    boxSizing: 'border-box',
    height: '36px',
    padding: '0 16px',
    border: 'none',
    borderRadius: '10px',
    fontFamily: 'inherit',
    fontSize: '13px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  }, [
    m('ghost', { color: 'var(--dsw-alias-label-primary)', background: 'var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,0.08))' }),
    m('primary', { color: '#fff', background: 'var(--dsw-alias-bg-accent, #2f6feb)' }),
    m('danger', { color: '#fff', background: '#c0392b' }),
    m('disabled', { opacity: 0.5, cursor: 'not-allowed' }),
  ]),
])
